import { Schedule } from "../types";

export const scheduleData: Schedule[] = [
  {
    id: 1,
    title: '08/11',
    date: new Date(2021, 11, 8),
    lectures: [
      {
        id: 100,
        title: 'abertura',
        time: '14h - 15h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 101,
        title: 'Deep Learning na Prática com TensorFlow',
        time: '15h - 17h',
        speakers: ['Ygor Canalli'],
        description: 'O minicurso aborda os conceitos básicos de Redes Neurais e Deep Learning no framework TensorFlow em uma abordagem prática. Você pode acompanhar o curso interativamente através do Google Colab. Link para material do minicurso: https://bit.ly/3bNurop',
        speakersImage: ['ygor.jpg'],
        logoImage: 'logos/coppe_logo.png',
      },
      {
        id: 103,
        title: 'Intervalo',
        time: '17h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 104,
        title: 'A Segurança da Informação é responsabilidade de todos.',
        time: '18h - 19h',
        speakers: ['Meirylene Avelino'],
        description: 'Atualmente praticamente todos os setores do mercado possuem algum tipo de integração tecnológica com sistemas que são responsáveis por armazenar dados e informações considerados sigilosos para a empresa. A Segurança da Informação zela pela proteção da utilização ou do acesso não autorizado ao conteúdo considerado de valor para uma determinada entidade. Em meio a inúmeras vulnerabilidades e ataques que exploram essas brechas de segurança que é uma responsabilidade de todos nós. Essa palestra visa realizar uma breve introdução sobre alguns conceitos sobre o tema com um caráter de conscientização sobre essa área tão abrangente e mostrar como pequenas atitudes do dia a dia podem evitar grandes ataques.',
        speakersImage: ['meirylene.jpeg'],
        logoImage: 'logos/globo_logo.png',
      },
    ]
  },
  {
    id: 2,
    title: '09/11',
    date: new Date(2021, 11, 9),
    lectures: [
      {
        id: 200,
        title: 'Como é a atração de talentos de tecnologia para a Creditas? E o que valorizamos na hora de contratar?',
        time: '14h - 15h',
        speakers: ['Anderson Victor'],
        description: 'Como é a atração de talentos de tecnologia para a Creditas? E o que valorizamos na hora de contratar?',
        speakersImage: ['anderson.jpg'],
        logoImage: 'logos/creditas_logo.png',
      },
      {
        id: 201,
        title: 'Segurança Digital e Privacidade: Potências e perigos.',
        time: '15h - 16h',
        speakers: ['Gilberto Imbariê'],
        description: 'O que significa segurança no universo digital? A autonomia digital, você sabe navegar em segurança na internet? Como potencializar sua segurança nas redes?',
        speakersImage: ['gilberto.jpg'],
        logoImage: 'logos/its_logo.png',
      },
      {
        id: 202,
        title: 'Bate Papo de Carreira na Intelie',
        time: '16h - 17h',
        speakers: ['Gustavo Koltz', 'Hosana Gomes', 'Guilherme Andrade'],
        description: 'Os três convidados trarão experiências, dicas e compartilharão informações sobre suas trajetórias e carreira.',
        speakersImage: [],
        logoImage: 'logos/intelie_logo.png',
      },
      {
        id: 203,
        title: 'Intervalo',
        time: '17h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 204,
        title: 'Chatbots e música: Como criar um Digital Assistant para o meu Spotify?',
        time: '18h - 19h',
        speakers: ['Eliel Silva', 'Mateus Reolo'],
        description: 'O Oracle Digital Assistant permite a construção de interfaces de conversação baseadas em IA para aplicativos em nuvem e locais. Vamos demonstrar como desenvolvemos um Assistente Digital para interagir com o Spotify uma de uma forma customizada.',
        speakersImage: ['eliel.jpg', 'mateus.jpg'],
        logoImage: 'logos/oracle_logo.png',
      },
    ]
  },
  {
    id: 3,
    title: '10/11',
    date: new Date(2021, 11, 10),
    lectures: [
      {
        id: 300,
        title: 'Benchmark de Aplicações Python com pyperf',
        time: '14h - 15h',
        speakers: ['Miguel Brito'],
        description: 'Quem programa, seja por hobbie ou profissionalmente, muito provavelmente encontrará uma situação em que precisará melhorar o desempenho de seus programas. Antes de otimizarmos nosso código, precisamos saber medí-lo de uma forma confiável e correta. Para isso, precisamos de ferramentas apropriadas e confiáveis. Nesta palestra falarei sobre o pyperf, uma ferramenta para escrita, análise e comparação de desempenho de programas escritos em Python. Discutirei o porquê pyperf é uma alternativa mais apropriada do que o módulo time do Python, ou o timeit, e como você poderá fazer proveito de suas funcionalidades mais relevantes. ',        speakersImage: ['miguel.jpeg'],
        logoImage: 'logos/page_logo.png',
      },
      {
        id: 301,
        title: 'A Governança dos dados na Era da Inteligência Artificial',
        time: '15h - 16h',
        speakers: ['Lucas Cabral'],
        description: 'Será abordado um panorama geral do universo do big data em nosso atual contexto social, dilemas éticos do uso das tecnologias e como tudo isto pode ser aplicado em: Inteligência Artificial, Internet das coisas e Reconhecimento facial. Levando em consideração a implementação da LGPD.',
        speakersImage: ['lucas.jpg'],
        logoImage: 'logos/its_logo.png',
      },
      {
        id: 302,
        title: 'Jornada Digital do BTG Pactual, muito além do App',
        time: '16h - 17h',
        speakers: ['Mario Martins', 'Diego Borsato'],
        description: 'Você sabe o que está por trás de um aplicativo de Banco? Aqui no BTG Pactual, inovação é coisa séria! Por isso, vamos te contar como tudo acontece nessa palestra, explorando as principais tecnologias utilizadas hoje na empresa e como conseguimos nos posicionar como um dos Bancos Digitais mais inovadores do Brasil, que cresce sua base e nota de satisfação de clientes a cada dia.',
        speakersImage: ['mario.jpg', 'diego.jpg'],
        logoImage: 'logos/btg_logo.png',
      },
      {
        id: 303,
        title: 'Intervalo',
        time: '17h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 304,
        title: 'Aplicações de Data Science na Indústria: principais conceitos, estudos de caso e prática em linguagem R',
        time: '18h - 19h',
        speakers: ['Turíbio Tanus Salis'],
        description: 'Data Science é uma área de atuação profissional que tem atraído muito interesse tanto acadêmico quanto nas empresas. Estudos de caso em diferentes campos de atuação reportam benefícios alcançados por meio do processo de Data Science. No setor industrial já é possível verificar melhorias na qualidade dos produtos, segurança operacional e redução de custos nos processos. Em nossas discussões apresentaremos os principais conceitos envolvidos no processo de Data Science, alguns estudos de caso e um exemplo prático usando linguagem R',
        speakersImage: ['turibio.jpeg'],
        logoImage: 'logos/vallourec_logo.png',
      },
    ]
  },
  {
    id: 4,
    title: '11/11',
    date: new Date(2021, 11, 11),
    lectures: [
      {
        id: 400,
        title: 'O futuro está em suas mãos: a transformação digital na visão do desenvolvimento mobile',
        time: '14h - 15h',
        speakers: ['Andrei Pataquine Oliveira'],
        description: 'Vimos a transformação digital acontecer de forma acelerada devido a pandemia. Como isso afetou o desenvolvimento mobile? Quantos anos adiantamos e como as empresas têm lidado com esse avanço tecnológico e sua grande migração para o mundo mobile?',
        speakersImage: ['andrei.jpeg'],
        logoImage: 'logos/ci&t_logo.png',
      },
      {
        id: 401,
        title: 'Blockchain: a nova era',
        time: '15h - 16h',
        speakers: ['Thais Leal'],
        description: 'Vamos descobrir os antecedentes da blockchain, seu histórico de utilização e de que forma ocorreu sua expansão. Um panorama sobre a cultura blockchain e contratos inteligentes.',
        speakersImage: ['thais.png'],
        logoImage: 'logos/its_logo.png',
      },
      {
        id: 402,
        title: 'Como funciona uma das Health Techs que mais crescem no Brasil',
        time: '16h - 17h',
        speakers: ['Daniel Rocha'],
        description: 'Conheça as tecnologias e os processos do time de tecnologia da PEBMED, uma das Health Techs que mais crescem no Brasil.',
        speakersImage: ['daniel.png'],
        logoImage: 'logos/pebmed_logo.png',
      },
      {
        id: 403,
        title: 'Intervalo',
        time: '17h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 404,
        title: 'Internacionalização em microsserviços',
        time: '18h - 19h',
        speakers: ['Carlos Rios (Zanaca)'],
        description: 'Um panorama sobre os desafios e impactos no processo de transformar um ambiente de microsserviços para poder entender multi-idiomas e multimoedas dentro de um processo de internacionalização de marca e operação.',
        speakersImage: ['zanaca.jpg'],
        logoImage: 'logos/hurb_logo.png',
      },
    ]
  },
  {
    id: 5,
    title: '12/11',
    date: new Date(2021, 11, 12),
    isMarathon: true,
    lectures: [
      {
        id: 500,
        title: 'Freshman Contest UFRRJ 2021',
        time: '14h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
    ]
  },
  {
    id: 6,
    title: '13/11',
    date: new Date(2021, 11, 13),
    isMarathon: true,
    lectures: [
      {
        id: 600,
        title: 'Maratonou! UFRRJ Contest 2021',
        time: '13h - 18h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
      {
        id: 601,
        title: 'Encerramento',
        time: '18h - 19h',
        speakers: [],
        description: '',
        speakersImage: [],
        logoImage: '',
      },
    ]
  },
]

export const links = {
  'beginners_maratonou': 'https://docs.google.com/forms/d/1aqyeoKpJPe1e2j61tlCPLDjx9wr05mC1ASQWb26W4vU/edit',
  'maratonou': 'https://docs.google.com/forms/d/172lJylwGtIUPgBIFqIu6AKHtV1SO3U5GFK_hwiEvArw/edit',
}
